services:
  - type: web
    name: rcpie-tracker
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    releaseCommand: python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn RCPIE.wsgi
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "rcpie-tracker.onrender.com"
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
