# Generated by Django 5.0.7 on 2024-08-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0007_researchproposal_rc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='rc_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='rc_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
