# Generated by Django 5.0.7 on 2024-08-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0008_patent_rc_id_projectproposal_rc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
