# Generated by Django 5.0.4 on 2025-03-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0021_rename_co_author_patent_co_author_patent_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent_proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('patent_number', models.CharField(max_length=100, unique=True)),
                ('proof_pdf', models.FileField(upload_to='patent_proofs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
