# Generated by Django 5.0.4 on 2025-03-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0031_remove_departmentdrc_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentdrc',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='departmentdrc',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmentdrc',
            name='mob',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
