# Generated by Django 5.0.7 on 2025-04-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0050_emailsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='odeptstatus',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='EmailSettings',
        ),
        migrations.DeleteModel(
            name='MailMessage',
        ),
    ]
