# Generated by Django 5.0.4 on 2025-10-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0058_proposalproof_dcr_comment_proposalproof_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproposal',
            name='CMRIT_Citation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
