# Generated by Django 5.0.7 on 2024-08-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0002_patent'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='user_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RCPIEAPP.userprofile'),
            preserve_default=False,
        ),
    ]
