# Generated by Django 5.0.7 on 2024-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0003_patent_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
