# Generated by Django 5.0.7 on 2024-08-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0004_patent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='dcr_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
