# Generated by Django 5.0.7 on 2024-08-14 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0005_patent_dcr_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('faculty_included', models.CharField(max_length=255)),
                ('proposal_form', models.FileField(upload_to='proposals/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('dcr_comment', models.TextField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCPIEAPP.userprofile')),
            ],
        ),
    ]
