# Generated by Django 5.0.7 on 2024-08-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0006_projectproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproposal',
            name='rc_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
