# Generated by Django 5.0.7 on 2024-08-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0009_userprofile_is_approved_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproposal',
            name='Co_author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='ConferenceOrjournal_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='Forum_for_submission',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='corresponding_author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='plagiarism',
            field=models.FileField(default='', upload_to='research_papers/'),
            preserve_default=False,
        ),
    ]
