# Generated by Django 5.0.7 on 2024-08-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0010_researchproposal_co_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='Co_author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='corresponding_author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='plagiarism',
            field=models.FileField(default='', upload_to='research_papers/'),
            preserve_default=False,
        ),
    ]
