# Generated by Django 5.0.7 on 2024-08-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0011_projectproposal_co_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectproposal',
            name='Co_author',
        ),
    ]
