# Generated by Django 5.0.7 on 2024-08-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0012_remove_projectproposal_co_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='Co_author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patent',
            name='corresponding_author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patent',
            name='full_pdf',
            field=models.FileField(default='', upload_to='patent/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patent',
            name='keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='plagiarism',
            field=models.FileField(upload_to='Project/'),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='plagiarism',
            field=models.FileField(upload_to='plagiarism_research_papers/'),
        ),
    ]
