# Generated by Django 5.0.7 on 2025-01-07 05:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0013_patent_co_author_patent_corresponding_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchproposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Research Proposal', 'verbose_name_plural': 'Research Proposals'},
        ),
        migrations.RenameField(
            model_name='researchproposal',
            old_name='Co_author',
            new_name='co_author',
        ),
        migrations.RenameField(
            model_name='researchproposal',
            old_name='ConferenceOrjournal_name',
            new_name='conference_or_journal_name',
        ),
        migrations.RenameField(
            model_name='researchproposal',
            old_name='Forum_for_submission',
            new_name='forum_for_submission',
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='is_approved_by_rc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='is_plagiarism_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='is_sent_to_drc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='full_paper',
            field=models.FileField(blank=True, null=True, upload_to='research_papers/'),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='plagiarism',
            field=models.FileField(blank=True, null=True, upload_to='plagiarism_research_papers/'),
        ),
    ]
