# Generated by Django 5.0.7 on 2025-03-08 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0016_remove_chatmessage_receiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcid', models.CharField(max_length=50)),
                ('cmrit_faculties', models.TextField()),
                ('students_involved', models.TextField()),
                ('co_authors', models.TextField(blank=True, null=True)),
                ('journal_conference', models.CharField(max_length=255)),
                ('journal_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('accepted_date', models.DateField()),
                ('presented_date', models.DateField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('journal_type', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('None', 'None')], max_length=10)),
                ('isbn_doi', models.CharField(blank=True, max_length=255, null=True)),
                ('proof_link', models.URLField()),
                ('remarks', models.TextField()),
                ('published_site_link', models.URLField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
