# Generated by Django 5.0.7 on 2025-03-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0017_publishedpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpaper',
            name='paper_type',
            field=models.CharField(choices=[('Mendatory', 'Mendatory'), ('R_Load', 'R_Load')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
