# Generated by Django 5.0.7 on 2025-03-12 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0018_publishedpaper_paper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedpaper',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCPIEAPP.userprofile'),
        ),
    ]
