# Generated by Django 5.0.7 on 2025-03-17 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0020_alter_publishedpaper_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patent',
            old_name='Co_author',
            new_name='co_author',
        ),
        migrations.AddField(
            model_name='patent',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patent',
            name='email_id',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patent',
            name='novelty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='prior_art',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
