# Generated by Django 5.0.4 on 2025-03-18 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0022_patent_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent_proof',
            name='rc_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patent_proof',
            name='user_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RCPIEAPP.userprofile'),
            preserve_default=False,
        ),
    ]
