# Generated by Django 5.0.4 on 2025-03-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0023_patent_proof_rc_id_patent_proof_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent_proof',
            name='proof_pdf',
        ),
        migrations.AddField(
            model_name='patent_proof',
            name='proof_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
