# Generated by Django 5.0.4 on 2025-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0024_remove_patent_proof_proof_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent_proof',
            name='proof_link',
        ),
        migrations.AddField(
            model_name='patent_proof',
            name='proof_pdf',
            field=models.FileField(default='', upload_to='patent_proofs/'),
            preserve_default=False,
        ),
    ]
