# Generated by Django 5.0.4 on 2025-03-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0025_remove_patent_proof_proof_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='proof_link',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
