# Generated by Django 5.0.4 on 2025-03-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0026_projectproposal_proof_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='proof_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
