# Generated by Django 5.0.4 on 2025-03-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0027_alter_projectproposal_proof_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent_proof',
            name='proof_pdf',
        ),
        migrations.AddField(
            model_name='patent_proof',
            name='proof_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
