# Generated by Django 5.0.4 on 2025-03-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0028_remove_patent_proof_proof_pdf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentdrc',
            old_name='additional_field_for_department_drc',
            new_name='department_name',
        ),
        migrations.AddField(
            model_name='departmentdrc',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmentdrc',
            name='drc_head_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmentdrc',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
