# Generated by Django 5.0.4 on 2025-03-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0029_rename_additional_field_for_department_drc_departmentdrc_department_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentdrc',
            old_name='department_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='departmentdrc',
            old_name='contact_number',
            new_name='mob',
        ),
        migrations.RemoveField(
            model_name='departmentdrc',
            name='drc_head_name',
        ),
    ]
