# Generated by Django 5.0.4 on 2025-03-19 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0030_rename_department_name_departmentdrc_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentdrc',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentdrc',
            name='email',
        ),
        migrations.RemoveField(
            model_name='departmentdrc',
            name='mob',
        ),
        migrations.RemoveField(
            model_name='rcconvener',
            name='additional_field_for_rc_convener',
        ),
    ]
