# Generated by Django 5.0.4 on 2025-03-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0032_departmentdrc_department_departmentdrc_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdrc',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
