# Generated by Django 5.0.4 on 2025-03-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0033_alter_departmentdrc_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdepartmentdrchead',
            name='additional_field_for_other_department_drc_head',
        ),
        migrations.AddField(
            model_name='otherdepartmentdrchead',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='otherdepartmentdrchead',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherdepartmentdrchead',
            name='mob',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
