# Generated by Django 5.0.7 on 2025-03-26 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0038_enterprenuerproof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cunsultancyproof',
            name='proof_pdf_1',
            field=models.FileField(upload_to='consultancy_proofs/'),
        ),
        migrations.AlterField(
            model_name='enterprenuerproof',
            name='proof_pdf_1',
            field=models.FileField(upload_to='enterprenuer_proofs/'),
        ),
        migrations.CreateModel(
            name='InnovationProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation_title', models.CharField(max_length=255)),
                ('rc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('proof_pdf_1', models.FileField(upload_to='innovation_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
