# Generated by Django 5.0.7 on 2025-03-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0039_alter_cunsultancyproof_proof_pdf_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalproof',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCPIEAPP.userprofile'),
        ),
    ]
