# Generated by Django 5.0.7 on 2025-04-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0042_academiccoordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Academic Coordinator', 'Academic Coordinator'), ('Faculty', 'Faculty'), ('RC Convener', 'RC Convener'), ('Department DRC', 'Department DRC'), ('Other Department DRC Head', 'Other Department DRC Head')], max_length=50),
        ),
    ]
