# Generated by Django 5.0.7 on 2025-04-03 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0043_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccoordinator',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
