# Generated by Django 5.0.7 on 2025-04-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0044_academiccoordinator_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccoordinator',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/excel_files/'),
        ),
    ]
