# Generated by Django 5.0.7 on 2025-05-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0053_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproposal',
            name='research_type',
            field=models.CharField(choices=[('Mendatory Paper', 'Mendatory Paper'), ('R load Paper', 'R load Paper')], default='Mendatory Paper', max_length=20),
        ),
    ]
