# Generated by Django 5.0.7 on 2025-05-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0054_researchproposal_research_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproposal',
            name='research_type',
        ),
    ]
