# Generated by Django 5.0.7 on 2025-05-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0056_researchproposal_research_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='patent_type',
            field=models.CharField(choices=[('Mandatory Paper', 'Mandatory Paper'), ('R load Paper', 'R load Paper')], default='Mandatory Patent', max_length=20),
        ),
    ]
