# Generated by Django 5.0.7 on 2025-09-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0057_patent_patent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalproof',
            name='dcr_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalproof',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
