# Generated by Django 5.0.4 on 2025-10-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0059_researchproposal_cmrit_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproposal',
            name='research_domain',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
