# Generated by Django 5.0.4 on 2025-10-23 09:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0060_researchproposal_research_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeanResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='uploads/excel_files/')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RCPIEAPP.userprofile')),
            ],
        ),
    ]
