# Generated by Django 5.0.4 on 2025-10-28 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0062_drc_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Research_Dean', 'Research_Dean'), ('DRC_Member', 'DRC_Member'), ('Academic Coordinator', 'Academic Coordinator'), ('Faculty', 'Faculty'), ('RC Convener', 'RC Convener'), ('Department DRC', 'Department DRC'), ('Other Department DRC Head', 'Other Department DRC Head')], max_length=50),
        ),
        migrations.CreateModel(
            name='DRCMemberReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('drc_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCPIEAPP.drc_member')),
                ('research_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCPIEAPP.researchproposal')),
            ],
        ),
    ]
