# Generated by Django 5.0.4 on 2025-11-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0064_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('research', 'Research'), ('patent', 'Patent'), ('project', 'Project'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
