# Generated by Django 5.0.4 on 2025-11-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0065_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproposal',
            name='sent_to_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('research', 'Research'), ('patent', 'Patent'), ('project', 'Project'), ('enterprenuer', 'enterprenuer'), ('consultancy', 'consultancy'), ('innovation', 'innovation'), ('proposal', 'proposal')], default='other', max_length=20),
        ),
    ]
