# Generated by Django 5.0.4 on 2025-11-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0066_researchproposal_sent_to_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproposal',
            name='other_departments',
            field=models.ManyToManyField(blank=True, related_name='forwarded_proposals', to='RCPIEAPP.userprofile'),
        ),
    ]
