# Generated by Django 5.0.4 on 2025-11-21 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0067_researchproposal_other_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('drc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCPIEAPP.otherdepartmentdrchead')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCPIEAPP.researchproposal')),
            ],
            options={
                'unique_together': {('proposal', 'drc')},
            },
        ),
    ]
