# Generated by Django 5.0.4 on 2025-11-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0068_proposalrouting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='patent_type',
            field=models.CharField(choices=[('Mandatory Patent', 'Mandatory Patent'), ('I load Patent', 'I load Patent')], default='Mandatory Patent', max_length=20),
        ),
    ]
