# Generated by Django 5.0.4 on 2025-11-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0069_alter_patent_patent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='assigned_to_research_dean',
            field=models.BooleanField(default=False),
        ),
    ]
