# Generated by Django 5.0.4 on 2025-11-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0070_patent_assigned_to_research_dean'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='dean_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
