# Generated by Django 5.0.4 on 2025-12-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0071_patent_dean_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproposal',
            name='drc_member_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='drc_member_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
