# Generated by Django 5.0.4 on 2025-12-11 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0072_researchproposal_drc_member_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedpaper',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCPIEAPP.researchproposal'),
        ),
    ]
