# Generated by Django 5.0.4 on 2026-03-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0073_alter_publishedpaper_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='sent_to_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
