# Generated by Django 5.0.4 on 2026-03-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0074_patent_sent_to_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='cunsultancyproof',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='consultancy_proofs/'),
        ),
        migrations.AlterField(
            model_name='cunsultancyproof',
            name='proof_pdf_1',
            field=models.FileField(upload_to='consultancy_document/'),
        ),
    ]
