# Generated by Django 5.0.4 on 2026-03-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0075_cunsultancyproof_proof_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprenuerproof',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='enterprenuer_proofs/'),
        ),
        migrations.AlterField(
            model_name='cunsultancyproof',
            name='proof_pdf_1',
            field=models.FileField(blank=True, null=True, upload_to='consultancy_document/'),
        ),
        migrations.AlterField(
            model_name='enterprenuerproof',
            name='proof_pdf_1',
            field=models.FileField(blank=True, null=True, upload_to='enterprenuer_document/'),
        ),
    ]
