# Generated by Django 5.0.4 on 2026-03-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0076_enterprenuerproof_proof_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalproof',
            name='proof_pdf_1',
            field=models.FileField(blank=True, null=True, upload_to='proposal_proofs/'),
        ),
        migrations.AlterField(
            model_name='proposalproof',
            name='proof_pdf_2',
            field=models.FileField(blank=True, null=True, upload_to='proposal_proofs/'),
        ),
    ]
