# Generated by Django 5.0.4 on 2026-03-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0077_alter_proposalproof_proof_pdf_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalproof',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='consultancy_proofs/'),
        ),
    ]
