# Generated by Django 5.0.4 on 2026-03-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0078_proposalproof_proof_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalproof',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='proposal_proofs/'),
        ),
    ]
