# Generated by Django 5.0.4 on 2026-03-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0079_alter_proposalproof_proof_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='proof_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
