# Generated by Django 5.0.7 on 2026-07-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0082_alter_proposalrouting_drc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalrouting',
            name='drc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCPIEAPP.departmentdrc'),
        ),
    ]
