# Generated by Django 5.0.7 on 2026-07-22 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0083_alter_proposalrouting_drc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchproposal',
            options={},
        ),
        migrations.RenameField(
            model_name='proposalrouting',
            old_name='comment',
            new_name='drc_comment',
        ),
        migrations.AlterUniqueTogether(
            name='proposalrouting',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='CMRIT_Citation',
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='area',
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='conference_or_journal_name',
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='corresponding_author',
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='forum_for_submission',
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='is_approved_by_rc',
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='is_plagiarism_checked',
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='plagiarism',
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='research_domain',
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='proposalrouting',
            name='routing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='odept_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='plagiarism_report',
            field=models.FileField(default='', upload_to='plagiarism_reports/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proposalrouting',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='co_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='drc_member_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='full_paper',
            field=models.FileField(upload_to='research_papers/'),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='keywords',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='odeptstatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='other_departments',
            field=models.ManyToManyField(blank=True, related_name='other_dept_proposals', to='RCPIEAPP.userprofile'),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='rc_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='research_type',
            field=models.CharField(choices=[('Funded', 'Funded'), ('Non-Funded', 'Non-Funded')], max_length=50),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='status',
            field=models.CharField(default='Submitted', max_length=100),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.RemoveField(
            model_name='proposalrouting',
            name='timestamp',
        ),
    ]
