# Generated by Django 5.0.7 on 2026-07-22 03:21

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0084_alter_researchproposal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchproposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Research Proposal', 'verbose_name_plural': 'Research Proposals'},
        ),
        migrations.RenameField(
            model_name='proposalrouting',
            old_name='drc_comment',
            new_name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='proposalrouting',
            unique_together={('proposal', 'drc')},
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='odept_comment',
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='plagiarism_report',
        ),
        migrations.RemoveField(
            model_name='researchproposal',
            name='submission_date',
        ),
        migrations.AddField(
            model_name='proposalrouting',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='CMRIT_Citation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='area',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='conference_or_journal_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='corresponding_author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='forum_for_submission',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='is_approved_by_rc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='is_plagiarism_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='plagiarism',
            field=models.FileField(blank=True, null=True, upload_to='plagiarism_research_papers/'),
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='research_domain',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proposalrouting',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='co_author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='drc_member_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='full_paper',
            field=models.FileField(blank=True, null=True, upload_to='research_papers/'),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='keywords',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='odeptstatus',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='other_departments',
            field=models.ManyToManyField(blank=True, related_name='forwarded_proposals', to='RCPIEAPP.userprofile'),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='rc_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='research_type',
            field=models.CharField(choices=[('Mendatory Paper', 'Mendatory Paper'), ('R load Paper', 'R load Paper')], default='Mendatory Paper', max_length=20),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='proposalrouting',
            name='routing_date',
        ),
    ]
