# Generated by Django 5.0.7 on 2026-07-22 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCPIEAPP', '0085_alter_researchproposal_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalrouting',
            old_name='comment',
            new_name='drc_comment',
        ),
        migrations.AlterUniqueTogether(
            name='proposalrouting',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='OtherDepartmentDRCHead',
        ),
        migrations.RemoveField(
            model_name='proposalrouting',
            name='timestamp',
        ),
    ]
